CREATE TABLE IF NOT EXISTS users
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(254) NOT NULL UNIQUE,
    login    VARCHAR(100) NOT NULL UNIQUE,
    name     VARCHAR(255),
    birthday DATE,
    CONSTRAINT users_birthday_chk CHECK (birthday IS NULL OR birthday <= CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS friendships
(
    user_id   BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    CONSTRAINT pk_friendships PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_friendships_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_friendships_friend FOREIGN KEY (friend_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT friendships_self_chk CHECK (user_id <> friend_id)
);

CREATE TABLE IF NOT EXISTS mpa_ratings
(
    mpa_rating_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genres
(
    genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films
(
    film_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    description   TEXT,
    release_date  DATE         NOT NULL,
    duration      INT          NOT NULL,
    mpa_rating_id INT          NOT NULL,
    CONSTRAINT fk_films_mpa FOREIGN KEY (mpa_rating_id)
        REFERENCES mpa_ratings (mpa_rating_id),
    CONSTRAINT films_duration_chk CHECK (duration > 0),
    CONSTRAINT films_release_chk CHECK (release_date >= DATE '1895-12-28')
);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  BIGINT NOT NULL,
    genre_id INT    NOT NULL,
    CONSTRAINT pk_film_genres PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_film_genres_film FOREIGN KEY (film_id)
        REFERENCES films (film_id) ON DELETE CASCADE,
    CONSTRAINT fk_film_genres_genre FOREIGN KEY (genre_id)
        REFERENCES genres (genre_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_likes
(
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_film_likes PRIMARY KEY (film_id, user_id),
    CONSTRAINT fk_film_likes_film FOREIGN KEY (film_id)
        REFERENCES films (film_id) ON DELETE CASCADE,
    CONSTRAINT fk_film_likes_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_films_mpa ON films (mpa_rating_id);
CREATE INDEX IF NOT EXISTS idx_film_likes_user ON film_likes (user_id);
CREATE INDEX IF NOT EXISTS idx_film_genres_genre ON film_genres (genre_id);
CREATE INDEX IF NOT EXISTS idx_friendships_user ON friendships (user_id);
CREATE INDEX IF NOT EXISTS idx_friendships_friend ON friendships (friend_id);